name: rpcalclol
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.0.2+7

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6
  cloud_firestore: ^3.1.8
  flutter_native_splash: ^2.0.5
  url_launcher: ^6.0.20
  change_app_package_name: ^1.0.0
  in_app_purchase: ^3.0.0
  shared_preferences: ^2.0.13
 

  
flutter_native_splash:

  background_image: "images/splashLolCalc.png"
  android: true





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


